### ISSUE TITLE
GetInstalledCertificateIds.req response should be NotFound if no certificates can be found

### ISSUE THREAD

**Issue by Pietfried** [EVerest/libocpp#391]
Request from CSMS
Tx: `[2,"c29f28a0-5570-4564-9471-f54d8c2df76f","GetInstalledCertificateIds",{"certificateType":"CentralSystemRootCertificate"}]`

Response by client
Rx: `[3,"c29f28a0-5570-4564-9471-f54d8c2df76f",{"certificateHashData":[],"status":"Accepted"}]`

The JSON schema for GetInstalledCertificateIds.conf has certificateHashData having a minimum size of 1.
Response should be:
Rx: `[3,"c29f28a0-5570-4564-9471-f54d8c2df76f",{"status":"NotFound"}]`

with certificateHashData omitted rather than being empty.

**Comment by movhdi** [comment]
Hi Piet,
Is it like imposing a condition on the line of ChargePointImpl::handleGetInstalledCertificateIdsRequest where it is populating response.certificatehashdata? And the condition should be checking that the optional object has_value()?

https://github.com/EVerest/libocpp/blob/8d7642d823e3999c56c3f904537815d4c2e17bc7/lib/ocpp/v16/charge_point_impl.cpp#L2267C1-L2268C71

**Comment by Pietfried** [comment]
> Hi Piet, Is it like imposing a condition on the line of ChargePointImpl::handleGetInstalledCertificateIdsRequest where it is populating response.certificatehashdata? And the condition should be checking that the optional object has_value()?
> 
> https://github.com/EVerest/libocpp/blob/8d7642d823e3999c56c3f904537815d4c2e17bc7/lib/ocpp/v16/charge_point_impl.cpp#L2267C1-L2268C71

Hi movhdi, yes it should be checked if `certificate_hash_data_chains` is empty. In that case, we should return ǸotFound`.
