### ISSUE TITLE
CSR Key Size/Type support

### ISSUE THREAD

**Issue by AssemblyJohn** [EVerest/libocpp#403]
Add an extra function for generating a CSR leveraging all security features of libevse like RSA key size or key type (RSA/EC):
https://github.com/EVerest/libevse-security/blob/e564e87e515b254af9dbdf9aaee5c435ebdde1e4/lib/evse_security/evse_security.cpp#L575

The values should be configurable.

**Comment by marcemmers** [comment]
I was also just looking into this and thought we might be able to do autodetection for determining the key type. I couldn't find out a way to do it though so a configuration item for this probably makes sense.
