### ISSUE TITLE
Extend Network Connection Profiles

### ISSUE THREAD

**Issue by SNSubramanya** [EVerest/libocpp#408]
To extend network connection profile for a more optional fine-grain control the following **optional** API interfaces need to be added:

1. Set up an interface. A callback can be implemented to set up the interface. For example, if the interface is a modem, it must first be enabled before it is possible to connect to that interface. 
2. Force close the web socket. Can be used to force the web socket to close when the low-level network interface goes down. This is much faster than waiting for a web socket timeout.
3. Switch to a higher priority interface. Normally, if libocpp is connected with a network connection profile, it will not disconnect. However, there may be a situation where libocpp is connected to a profile with priority 2 or lower, and you find out at system level that an interface (with a higher priority) has changed and is now up. In this case, you may want to tell libocpp that the higher priority priority interface is up and that it can try to connect to it. 
4. Connected and disconnected web socket callback. It will provide the network slot in these callbacks so that you can keep the network connection in use (e.g. do not disable the modem) or deactivate it if necessary.

**Comment by WilcodenBesten** [comment]
Picking this up and updated the description. I'll keep #410 open for now, but i'll make a new branch on top of #748 as it's very much outdated.
