### ISSUE TITLE
v16 `SmartChargingHandler::clear_all_profiles_with_filter` filtering incorrectly

### ISSUE THREAD

**Issue by couryrr-afs** [EVerest/libocpp#432]
I'm currently working on tests for the `SmartChargingHandler::clear_all_profiles_with_filter` function, which involves data setup, checks, and a call to `SmartChargingHandler::clear_profiles` based on certain conditions.

The current tests can be found on this [branch](https://github.com/US-JOET/libocpp/blob/09c4de829a3fc4233d3c94530be2b2e8aa8fb272/tests/lib/ocpp/v16/test_smart_charging_handler.cpp#L672).

As part of the setup, I have two connectors with ids 100 and 200, each having two profiles with ids 1 and 2.

I'm using the `add_tx_profile` method and verifying with `get_valid_profiles` to ensure the profiles are added, with each connector having two profiles.

The test sets `check_id_only` to `false` so that all filter tokens should be applied, not just the `profile_id`.

In the first test case, a call to `clear_all_profiles_with_filter(1, connector_id_1, std::nullopt, std::nullopt, false)` is made. The expected outcome is that only the profile with connector id 100 and profile id 1 should be deleted. Therefore, we expect connector_id 100 to have 1 profile left, and connector_id 200 to have 2 profiles left. However, the observed outcome is that all profiles on both connectors are deleted.

The second test case has the same data setup and calls `clear_all_profiles_with_filter(999, connector_id_1, std::nullopt, std::nullopt, false)`. This case does not match any combination, so the expected behavior is that connector_id 100 has 2 profiles left, and connector_id 200 has 2 profiles left. However, connector_id 100 has all profiles removed, and connector_id 200 did not have any deleted.

**Comment by couryrr-afs** [comment]
@Pietfried this is the issue that I brought up on the call today. If you could verify the data setup and the outcome that would be appreciated. Let me know if you have issue accessing the forked repo.

**Comment by Pietfried** [comment]
Hi @couryrr-afs , thanks for bringing this up. I had a look into the specification and found this definition in the OCPP1.6 errata sheet: v4.0 Release, 2019-10-23:

Old text:
> The Central System can use this message to clear (remove) either a specific charging profile (denoted by id) or a selection of charging profiles that match with the values of the optional connectorId, stackLevel and chargingProfilePurpose fields.

New text:
> The Central System can use this message to clear (remove) either a specific charging profile (denoted by id) or a selection of charging profiles that match (logical AND) with the values of the optional connectorId, stackLevel and chargingProfilePurpose fields. If no fields are provided, then all charging profiles will be cleared. If id is specified, then all other fields are ignored.

If you consider the combination of `charge_point_impl.cpp` and `smart_charging.cpp` the handling of the ClearChargingProfile.req message looks correct to me but I admit that the `clear_all_profiles_with_filter` and `clear_profiles` is not well documented, reading through the methods can be misleading and the methods should be refactored.

To me it looks like the `check_id_only` flag is superflous. Either `profile_id_opt` has a value and in this case all other fields are ignored or `profile_id_opt` doesnt have a value and in this case we need to check the logical AND between the rest of the fields.

If you look into the invocation of `clear_all_profiles_with_filter` within `charge_point_impl.cpp` you can see that there is never a combination of `check_id_only` == `false` AND `profile_id_opt` being set. For this reason the implementation works, but this combination is exactly what you are testing in the test cases and thats causing your test cases to fail.

As a solution, I would suggest to remove the `check_id_only` argument from the methods and document its behavior as specified in the errata.

**Comment by couryrr-afs** [comment]
@Pietfried thank you for the quick feedback. While that does seem to invalidate my current test setup the method that is exposed would allow for this kind of invalid request to occur and produce an undesired outcome. I do not think anything is stopping the incoming message from setting all of these fields. It seems that there needs to be a more strict check that the `profile_id_opt` is present and perhaps a method to handle specifically that case (a better named function call) and the other where the other filters are applied.

This seems related to this case although not the same functional requirement. I had the following text in 2.0.1 highlighted in the spec for K09 - Get Charging Profiles - Requirements 

>These fields are filter values of equal importance, but because a chargingProfileId uniquely identifies a charging profile, the other fields are not needed if chargingProfileIds are used.

Should the interpretation of this mean that `chargingProfileId` needs to be unique in all cases even across connectors?

**Comment by Pietfried** [comment]
> @Pietfried thank you for the quick feedback. While that does seem to invalidate my current test setup the method that is exposed would allow for this kind of invalid request to occur and produce an undesired outcome. I do not think anything is stopping the incoming message from setting all of these fields. It seems that there needs to be a more strict check that the `profile_id_opt` is present and perhaps a method to handle specifically that case (a better named function call) and the other where the other filters are applied.
> 
> This seems related to this case although not the same functional requirement. I had the following text in 2.0.1 highlighted in the spec for K09 - Get Charging Profiles - Requirements
> 
> > These fields are filter values of equal importance, but because a chargingProfileId uniquely identifies a charging profile, the other fields are not needed if chargingProfileIds are used.

@couryrr-afs I like the idea of refactoring the filter methods by splitting them up and renaming them to make them easier to read and more verbose. 

> 
> Should the interpretation of this mean that `chargingProfileId` needs to be unique in all cases even across connectors?

Yes that would also be my interpretation. But you can not forbid the CSMS to set charging profiles with the same `chargingProfileId` on different connectors.

**Comment by couryrr-afs** [comment]
@Pietfried than you for confirming the interpretation. It has been a question on our team.

A refactor of the method to two and perhaps some guards around if the profile id is sent that is the only token that will do the clearing. Right now it appears the oddity came from the case that I could pass all token and it would filter on all of the tokens.
