### ISSUE TITLE
No parameter filter is clearing all profiles for `SmartChargingHandler::clear_all_profiles_with_filter`

### ISSUE THREAD

**Issue by couryrr-afs** [EVerest/libocpp#446]
I was adding unit test to `SmartChargingHandler::clear_all_profiles_with_filter` on the branch [couryrr/adding-k01-unit-tests](https://github.com/US-JOET/libocpp/tree/couryrr/adding-k01-unit-tests). There is a skipped case for sending over no parameters to the filter which is removing all of the profiles on all connectors. Since this is a call to clear with filters I wanted to confirm that this was the expected behavior.

There is a section in the spec that seems to support this use case. This issue I see is that there is no feedback to the client that they are about to delete everything:

> If the Central System wishes to clear some or all of the charging profiles that were previously sent the Charge
Point, it SHALL use the ClearChargingProfile.req PDU.

**Comment by Pietfried** [comment]
OCPP1.6 Errata v4.0:

> 3.25. Page 47, section 5.5: Unclear how to match fields in a ClearChargingProfile
request
If no fields are specified in the ClearChargingProfile.req message, then Charge Point SHALL
clear all ChargingProfiles. If one or more fields are specified in the ClearChargingProfile.req
message, then Charge Point SHALL clear all ChargingProfiles that match (logical AND) all of the
provided fields.
