### ISSUE TITLE
libocpp verify_csms_cn seems to be unable to handle wildcard domain certificate

### ISSUE THREAD

**Issue by lategoodbye** [EVerest/libocpp#494]
### OCPP Version

OCPP1.6, OCPP2.0.1

### Describe the bug

Our customer tried to use our EVerest image (EVerest-core 2024.01) with Security profile 2, but it fails during the CSMS CN validation.

```
Feb 25 10:47:02 tarragon manager[4859]: 2024-02-25 10:47:02.344092 [INFO] OCPP0:OCPP       :: Connecting TLS websocket to uri: wss://cpc.gridfluxx.com/gridfluxx/????????? with security-profile 2
Feb 25 10:47:02 tarragon manager[4864]: 2024-02-25 10:47:02.409081 [INFO] cb_tarragon_dri  :: handle_pwm_off: Setting new duty cycle of 100.00%
Feb 25 10:47:02 tarragon manager[4859]: 2024-02-25 10:47:02.566583 [INFO] OCPP0:OCPP       :: Found 0 charging profile(s) in the database
Feb 25 10:47:02 tarragon manager[4859]: 2024-02-25 10:47:02.572983 [INFO] OCPP0:OCPP       :: OCPP initialized
Feb 25 10:47:02 tarragon manager[4859]: 2024-02-25 10:47:02.577917 [INFO] OCPP0:OCPP       :: Processing queued session event for evse_id: 1, event: Enabled
Feb 25 10:47:02 tarragon manager[4859]: 2024-02-25 10:47:02.584815 [INFO] OCPP0:OCPP       :: Processing queued session event for evse_id: 1, event: Enabled
Feb 25 10:47:02 tarragon manager[4864]: 2024-02-25 10:47:02.669221 [INFO] cb_tarragon_dri  :: handle_pwm_off: Setting new duty cycle of 100.00%
Feb 25 10:47:02 tarragon manager[4865]: 2024-02-25 10:47:02.707731 [WARN] connector_1:Evs virtual bool module::evse::evse_managerImpl::handle_external_ready_to_start_charging() :: Ignoring external ready to start charging command, this could be a configuration issue. Please check if 'external_ready_to_start_charging' is set to true if you want to use this feature.
Feb 25 10:47:02 tarragon manager[4798]: 2024-02-25 10:47:02.822629 [INFO] manager          :: There are no errors of type evse_manager/MREC4OverCurrentFailure and of module connector_1->evse, so no errors are cleared
Feb 25 10:47:02 tarragon manager[4859]: 2024-02-25 10:47:02.881701 [WARN] OCPP0:OCPP      bool ocpp::WebsocketTLS::verify_csms_cn(const string&, bool, boost::asio::ssl::verify_context&) :: FQDN 'cpc.gridfluxx.com' does not match CN '*.gridfluxx.com' or any alternative names '*.gridfluxx.com'
```

### To Reproduce

Configure a OCPP CSMS with Security profile 2 and a wildcard domain certificate and try to connect.

### Anything else?

This issue has been workarounded by setting VerifyCsmsCommonName to false.

**Comment by Pietfried** [comment]
Thanks for reporting, this is a known issue. Glad you found out how to mitigate using the `VerifyCsmsCommonName` configuration key

**Comment by lategoodbye** [comment]
Sorry, i didn't find it. Is there a document or an issue which already describe it?

**Comment by Pietfried** [comment]
Sorry, it's known but net yet documented as an issue, so thanks for bringing this up! We will start to work on a fix

**Comment by barsnick** [comment]
You may want to use Boost's/Asio's [ssl::rfc2818_verification](https://live.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/ssl__rfc2818_verification.html) or better [ssl::host_name_verification](https://live.boost.org/doc/libs/1_73_0/doc/html/boost_asio/reference/ssl__host_name_verification.html), introduced in Boost 1.73.0.

Or if you're building your own: The [latter implementation uses](https://github.com/boostorg/asio/blob/develop/include/boost/asio/ssl/impl/host_name_verification.ipp) OpenSSL's [X509_check_ip_asc](https://www.openssl.org/docs/manmaster/man3/X509_check_ip_asc.html) and [X509_check_host](https://www.openssl.org/docs/manmaster/man3/X509_check_host.html). Both are available in OpenSSL v1.0.2+, and you wouldn't have to rely on Boost >= 1.73.0.

**Comment by AssemblyJohn** [comment]
I would recommend testing with branch: https://github.com/EVerest/libocpp/tree/bugfix/494-libocpp-verify_csms_cn_wildcard

Please, let me know if it fixed the problem for you.

**Comment by lategoodbye** [comment]
@AssemblyJohn Thanks, we will try to test this today.

Regardless of the results, i've two questions since this is not clear from the commit message:

- Why must this be configurable?
- Why is the support for wildcards disabled per default?

**Comment by AssemblyJohn** [comment]
> @AssemblyJohn Thanks, we will try to test this today.
> 
> Regardless of the results, i've two questions since this is not clear from the commit message:
> 
> * Why must this be configurable?
> * Why is the support for wildcards disabled per default?

From our experience, when there is a feature that is not required by everybody, it is better to keep the legacy functionality in place since it provides stable results. Adding/removing new functionality most of the times has unforeseen side effects, and it is better to keep something disabled until it is absolutely needed.

**Comment by Pietfried** [comment]
> @AssemblyJohn Thanks, we will try to test this today.
> 
> Regardless of the results, i've two questions since this is not clear from the commit message:
> 
> * Why must this be configurable?
> * Why is the support for wildcards disabled per default?

Its disabled by default because of this OCPP2.0.1 requirement:

> A00.FR.412: The Charging Station SHALL verify that the commonName matches the
CSMS’s FQDN.

**Comment by AssemblyJohn** [comment]
> A00.FR.412

I don't understand from the requirement that wildcards are forbidden, so it is unclear. In that case better to have it off :)

**Comment by Pietfried** [comment]
> > A00.FR.412
> 
> I don't understand from the requirement that wildcards are forbidden, so it is unclear. In that case better to have it off by default :)

In my view FQDN and CN do not **match** if wildcards are used.

**Comment by lategoodbye** [comment]
Okay, maybe this is something which could be clarified with the OCA afterwards. In this case the current approach makes perfect sense.

**Comment by lategoodbye** [comment]
```
Mar 05 13:46:28 tarragon manager[7745]: terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::type_error'
Mar 05 13:46:28 tarragon manager[7745]:   what():  [json.exception.type_error.302] type must be boolean, but is null
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.619527 [CRIT] manager         int boot(const boost::program_options::variables_map&) :: Module ocpp (pid: 7745) exited with status: 6. Terminating all modules.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.632296 [INFO] manager          :: SIGTERM of child: api_1 (pid: 7736) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.639616 [INFO] manager          :: SIGTERM of child: api_2 (pid: 7737) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.651025 [INFO] manager          :: SIGTERM of child: auth (pid: 7738) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.666370 [INFO] manager          :: SIGTERM of child: connector_1 (pid: 7739) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.681063 [INFO] manager          :: SIGTERM of child: connector_2 (pid: 7740) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.690128 [INFO] manager          :: SIGTERM of child: energy_manager (pid: 7741) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.701601 [INFO] manager          :: SIGTERM of child: evse_security (pid: 7742) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.710902 [INFO] manager          :: SIGTERM of child: grid_connection_point (pid: 7743) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.720493 [INFO] manager          :: SIGTERM of child: hmiled (pid: 7744) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.731589 [INFO] manager          :: SIGTERM of child: powermeter (pid: 7746) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.738051 [INFO] manager          :: SIGTERM of child: serialcommhub_x7 (pid: 7747) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.747850 [INFO] manager          :: SIGTERM of child: system (pid: 7748) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.754604 [INFO] manager          :: SIGTERM of child: system_aggregator (pid: 7749) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.764467 [INFO] manager          :: SIGTERM of child: tarragon_bsp (pid: 7750) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.770558 [INFO] manager          :: SIGTERM of child: tarragon_pluglock (pid: 7751) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.778269 [INFO] manager          :: SIGTERM of child: token_provider_1 (pid: 7752) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.787293 [INFO] manager          :: SIGTERM of child: token_provider_2 (pid: 7753) succeeded.
Mar 05 13:46:28 tarragon manager[7674]: 2024-03-05 13:46:28.787687 [CRIT] manager         int boot(const boost::program_options::variables_map&) :: Exiting manager.
Mar 05 13:46:28 tarragon systemd[1]: everest.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 13:46:28 tarragon systemd[1]: everest.service: Killing process 7676 (controller) with signal SIGKILL.
Mar 05 13:46:28 tarragon systemd[1]: everest.service: Failed with result 'exit-code'.
Mar 05 13:46:29 tarragon systemd[1]: everest.service: Scheduled restart job, restart counter is at 1.
Mar 05 13:46:29 tarragon systemd[1]: Stopped EVerest.
Mar 05 13:46:29 tarragon systemd[1]: Started EVerest.
```
It seems there is no proper handling in case the no parameter is absent. Btw please add a reference to this issue within the commit messages.

**Comment by lategoodbye** [comment]
Okay, i tested the good case with a wildcard domain and got the following result:
```
Mar 05 16:34:35 tarragon manager[9441]: 2024-03-05 16:34:35.342731 [INFO] ocpp:OCPP        :: Reconnecting to TLS websocket at uri: wss://xxxxxxxxx with security profile: 2
Mar 05 16:34:36 tarragon manager[9441]: 2024-03-05 16:34:36.197349 [INFO] ocpp:OCPP        :: OCPP client successfully connected to TLS websocket server
```

I also disabled wildcard support and got the following error:
```
Mar 05 16:35:50 tarragon manager[9770]: 2024-03-05 16:35:50.094259 [ERRO] ocpp:OCPP       void ocpp::WebsocketBase::log_on_fail(const std::error_code&, const boost::system::error_code&, int) :: Failed to connect to websocket server, error_code: 8, reason: TLS handshake failed, HTTP response code: 0, category: websocketpp.transport.asio.socket, transport error code: 167772567, Transport error category: asio.ssl
```

I'm not sure this is how it should looks like.

**Comment by AssemblyJohn** [comment]
Try inserting the full domain name into the connection attempt (without wildcard). After that try with the wildcard. Maybe try replacing: X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS with X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS

**Comment by lategoodbye** [comment]
> Try inserting the full domain name into the connection attempt (without wildcard). After that try with the wildcard.

Sorry, i don't understand your request. The wildcard is within the certificate, so i always need to define a FQDN in the CentralSystemURI. But i successful tested a FQDN with wildcard certificate (security level 2, see good case above) and a FQDN with security level 0.

> Maybe try replacing: X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS with X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS

Does it mean you are not sure about the implementation and you didn't test it by yourself?

**Comment by AssemblyJohn** [comment]
> > Try inserting the full domain name into the connection attempt (without wildcard). After that try with the wildcard.
> 
> Sorry, i don't understand your request. The wildcard is within the certificate, so i always need to define a FQDN in the CentralSystemURI. But i successful tested a FQDN with wildcard certificate (security level 2, see good case above) and a FQDN with security level 0.
> 
> > Maybe try replacing: X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS with X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS
> 
> Does it mean you are not sure about the implementation and you didn't test it by yourself? No offense, i just want to know.

Hello! Thank you for the clarifications. I have only tested with 3 back-ends, however if I don't test with the exact setup that you are using, there is always a margin for error. If you would like full guarantees, you have to offer us your full setup for a test environment.

**Comment by lategoodbye** [comment]
Okay, maybe i wasn't clear with my test result. Good case (Fix for wildcard) works as expected. I was only unsure about the resulting error (not really helpful as before) in the bad case (wildcard domain, but VerifyCsmsAllowWildcards = false).

Since you already tested with 3 backends this is great.

**Comment by AssemblyJohn** [comment]
Yes, I've also noticed the less verbose error, however we plan to switch from websocket++ to libwebsockets that has a lower-level implementation and will output a clearer error.

**Comment by lategoodbye** [comment]
Okay. So i'm fine with this branch and its commits except of the missing reference to this bug.
