### ISSUE TITLE
Add IdTagInfo to startTransaction.conf callbacks

### ISSUE THREAD

**Issue by bWF0dGhpYXMK** [EVerest/libocpp#499]
### OCPP Version

OCPP1.6

### Describe the problem

The startTransaction.conf contains idTagInfo, 

### Describe your solution

It is added as return value to the related callbacks transactionStarted and pauseCharging)
see PR: https://github.com/EVerest/libocpp/pull/498

**Comment by Pietfried** [comment]
Solved with https://github.com/EVerest/libocpp/pull/498
