### ISSUE TITLE
Libwebsockets: be able to set an interface or ip address to connect to.

### ISSUE THREAD

**Issue by maaikez** [EVerest/libocpp#542]
### OCPP Version

OCPP1.6, OCPP2.0.1

### Describe the problem

For the network connection profiles refactoring (issue #408), we want to be able to set an interface the websocket has to use to connect to. It should be able to set an interface or the ip address of the interface. It is possible an interface has two ip addresses (one link local and one 'normal' ip address) so it must be possible to set the ip address the websocket needs to connect to. Also, if you do nothing, the websocket library might just choose to use for example the wired interface to connect while you want to connect via the modem. 

So the feature request is to make sure it is possible to set an ip address of in interface which the websocket will use to connect to the backoffice.

### Describe your solution

In libwebsockets, in the `lws_context_creation_info` struct, you can set the `iface`, which can be an ip address or the interface name. It is available when `LWS_WITH_NETWORK` is defined. However, if you only set this `iface`, it seems the websocket still connects via another interface (tested with a network connection profile set to a modem with a local ip address that is not available via the outside world, so it should not be able to connect in that case). According to the documentation, we should set `bind_iface` in the same struct to `1` to make this work (this should call `setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, vhost->iface, (socklen_t)strlen(vhost->iface)`, found in `unix-sockets.c`). However, if I try that, the websocket can not connect with the backend at all anymore. I did not find out why yet.

**Comment by maaikez** [comment]
It looks like setsockopt (SO_BINDTODEVICE) does not work with an ip address, so I think we should not set that either. It is unclear to me why setting the ip address in `iface` does not work, because I think it uses the 'bind' call underwater, which should just work.

**Comment by AssemblyJohn** [comment]
I see there are two 'iface' definitions, one in 'lws_client_connect_info' and one in 'lws_context_creation_info'. Will start looking into the issue with both IP binding and interface name binding.

Note: as per some posts, the 'SO_BINDTODEVICE' requires elevated permissions and must be supported by the OS.
Note2: CAP_NET_RAW capability is also required
