### ISSUE TITLE
Error During CMake command Execution

### ISSUE THREAD

**Issue by tefelberson** [EVerest/libocpp#590]
I'm encountering an issue while installing MaEve, I'm encountering an error exactly while executing the "cmake .." .
It seems that cmake is unable to locate the everest-cmake package during the configuration phase.

Could you provide guidance on how to resolve this error? I'm not sure why cmake is unable to find the everest-cmake package, as I haven't explicitly installed it. I'd appreciate any help in resolving this issue and configuring my project correctly.

![Capture d'écran 2024-04-29 011952](https://github.com/EVerest/libocpp/assets/73689893/bfc9b89c-ee1c-4df5-80f5-dce0bbbdc712)

**Comment by Pietfried** [comment]
Hi @tefelberson , try to check out `https://github.com/EVerest/everest-cmake` in the same workspace where libocpp is checked out.

**Comment by tefelberson** [comment]
I installed it directly in the Libocpp directory present in the Everest folder and it works.
