### ISSUE TITLE
 Execute on changeavailability for connector 0 callback

### ISSUE THREAD

**Issue by bWF0dGhpYXMK** [EVerest/libocpp#608]
### OCPP Version

OCPP1.6

### Describe the problem

In case of changeAvailablilty.req the callback for connector 0 is not present. This information is then not available at business-code level.

### Describe your solution

Execute callback also for connector 0. See https://github.com/EVerest/libocpp/pull/607

**Comment by Pietfried** [comment]
Solved with https://github.com/EVerest/libocpp/pull/607
