### ISSUE TITLE
v1.6: On call of onEnable, on disable from business-logic, persist this change inside database

### ISSUE THREAD

**Issue by bWF0dGhpYXMK** [EVerest/libocpp#626]
### OCPP Version

OCPP1.6

### Describe the problem

If the businesslogic decides to disable/enable a charger point, the change has to be reboot save. 
- E.g. a firmware update happens which sets the station to onDisable, on reboot, it would start again in operative, and requires again a set into unavailable.
- Conceptional the station shall be set to be inoperative w.o. backend command, and this inoperative state shall be persist after reboot.

### Describe your solution

Store into database. see https://github.com/EVerest/libocpp/pull/625

**Comment by Pietfried** [comment]
> ### OCPP Version
> OCPP1.6
> 
> ### Describe the problem
> If the businesslogic decides to disable/enable a charger point, the change has to be reboot save.
> 
> * E.g. a firmware update happens which sets the station to onDisable, on reboot, it would start again in operative, and requires again a set into unavailable.
> * Conceptional the station shall be set to be inoperative w.o. backend command, and this inoperative state shall be persist after reboot.
> 
> ### Describe your solution
> Store into database. see #625
> 
> ### Additional context
> _No response_

Hi @bWF0dGhpYXMK , the [start function](https://github.com/EVerest/libocpp/blob/main/include/ocpp/v16/charge_point.hpp#L80) of the `charge_point.hpp` allows you to transmit the connector states on startup. Your business logic can therefore persist the state if it is required and libocpp can send the desired states after the BootNotification.
