### ISSUE TITLE
v1.6: Reject call of RemoteStart.req with negative connector

### ISSUE THREAD

**Issue by bWF0dGhpYXMK** [EVerest/libocpp#628]
### OCPP Version

OCPP1.6

### Describe the problem

A negative connectorId inside the RemoteStart.req can lead to unexpected behavior.

### Describe your solution

Reject the call. https://github.com/EVerest/libocpp/pull/627

**Comment by Pietfried** [comment]
Fixed with https://github.com/EVerest/libocpp/pull/627
