### ISSUE TITLE
v1.6: Persist scheuduled changeAvailablity.req

### ISSUE THREAD

**Issue by bWF0dGhpYXMK** [EVerest/libocpp#630]
### OCPP Version

OCPP1.6

### Describe the problem

If a transaction is running and a changeAvailabilty.req is performed, it is answerd with "scheduled". This information is not stored persistently. If the station observes a powerloss the "scheduled" changeAvaiablity is lost. 

### Describe your solution

Store the "changeAvailablity.req" alread in database. https://github.com/EVerest/libocpp/pull/629

**Comment by Pietfried** [comment]
Fixed with https://github.com/EVerest/libocpp/pull/629
