### ISSUE TITLE
Error management when received incorrect OCPP message.

### ISSUE THREAD

**Issue by clementrey-dev** [EVerest/libocpp#649]
### OCPP Version

OCPP1.6

### Describe the problem

When the content of the OCPP message is corrupted or ill-formated (For example  a payload such [2,"id",Reset,{"type" : "Had"}, The ocpp module stop with all other modules.

### Describe your solution

Instead of stopping the OCPP  would it be possible to send back a message of type ["4","id","error message"] to the CMS ?

**Comment by Pietfried** [comment]
Hi @clementrey-dev , this should be solved by https://github.com/EVerest/libocpp/pull/618/files . This has been merged yesterday.

**Comment by Pietfried** [comment]
> Good news, Can I just update the file https://github.com/EVerest/everest-core/blob/54ea32be8432d9292879ed0f36e181a6b37e3266/dependencies.yaml with your commit hash or this will be more complex to test it ?

Yes you could do this or if you build locally you can simply check out libocpp with the desired commit/branch alongside everest-core. Local check outs are always prefered over the specification in the dependencies.yaml

**Comment by clementrey-dev** [comment]
Hello,

Thank you,
I test it and it works as expected.

Best Regards
Clement
