### ISSUE TITLE
init_websocket throws exception when all networkprofilexcsmsurl values are empty

### ISSUE THREAD

**Issue by ghost** [EVerest/libocpp#667]
### OCPP Version

OCPP2.0.1

### Describe the bug

`void ChargePoint::init_websocket() {

    if (this->device_model->get_value<std::string>(ControllerComponentVariables::ChargePointId).find(':') !=
        std::string::npos) {
        EVLOG_AND_THROW(std::runtime_error("ChargePointId must not contain \':\'"));
    }

    const auto configuration_slot =
        ocpp::get_vector_from_csv(
            this->device_model->get_value<std::string>(ControllerComponentVariables::NetworkConfigurationPriority))
            .at(this->network_configuration_priority);`

when all `networkprofilexcsmsurl` values are empty, `this->device_model->get_value<std::string>(ControllerComponentVariables::NetworkConfigurationPriority)` also returns an empty string. Accessing it with `at(this->network_configuration_priority); `(which is zero in this case) causes the `vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)` error message.

**Comment by shingoxx222** [comment]
#669
