### ISSUE TITLE
OCTT - TC_E_22_CS - TC_E_24_CS - TC_E_25_CS - Testcases Fail

### ISSUE THREAD

**Issue by msozen** [EVerest/libocpp#687]
### OCPP Version

OCPP2.0.1

### Describe the bug

Everest version: Everest 2024.5.0
Ocpplib version: 0.12.0
---------------------------------------
When we run this test case on the OCTT tool, it continues to the end of the test cycle but it fails with reason:
"Message field triggerReason should be ChargingStateChanged."

While the actual triggerReason we get back from the charger to the OCTT tool is "triggerReason": "StopAuthorized".

OCTT Logs:
[pdspe_base_TC_E_22_CS2024-06-27T11_21_03.889802.log](https://github.com/user-attachments/files/16012835/pdspe_base_TC_E_22_CS2024-06-27T11_21_03.889802.log)

[pdspe_base_TC_E_24_CS2024-06-27T11_49_12.738301.log](https://github.com/user-attachments/files/16012975/pdspe_base_TC_E_24_CS2024-06-27T11_49_12.738301.log)

[pdspe_base_TC_E_25_CS2024-06-17T12_06_53.615617.log](https://github.com/user-attachments/files/16012979/pdspe_base_TC_E_25_CS2024-06-17T12_06_53.615617.log)

### To Reproduce

Execute the testcase in OCTT tool:
OCPP Version : OCPP 2.0.1
Build Number : Release_2024-04_v2

**Comment by Pietfried** [comment]
Hi @msozen , thanks for reporting this! I could reproduce the issue and we are working on a fix. Looks like the issue was introduced with https://github.com/EVerest/libocpp/pull/594
