### ISSUE TITLE
ResetResponse in response to ResetRequest with `evseId` != 0 does not take `AllowReset` into consideration

### ISSUE THREAD

**Issue by barsnick** [EVerest/libocpp#700]
### OCPP Version

OCPP2.0.1

### Describe the bug

When the CSMS sends a ResetRequest with `evseId` != 0, i.e. for a single EVSE, the ResetResponse is created with a `status` based on the result of the cmd `is_reset_allowed` to the `system` interface, so either `Accepted` or `Rejected`.

Yet even with the system interface, the OCPP module can have knowledge of whether this is allowed, by the variable `AllowReset` in the device model.

(This is a per-EVSE only value.)

> B11.FR.10
> When the Charging Station supports resetting of an individual EVSE
> The Charging Station SHOULD set the device model variable AllowReset to true for the EVSE.

(I read this as: It is not necessary for the CS to announce this.)

If this variable is actually set, I expect the OCPP module not to query the `system` interface, but instead respond based on this variable.

### Anything else?

The fix should probably look something like this (I cannot test building right now, and don't have a CSMS which can trigger a per-EVSE ResetRequest):

```diff
diff --git a/lib/ocpp/v201/charge_point.cpp b/lib/ocpp/v201/charge_point.cpp
index 8f74febf..a852aeee 100644
--- a/lib/ocpp/v201/charge_point.cpp
+++ b/lib/ocpp/v201/charge_point.cpp
@@ -2564,7 +2564,16 @@ void ChargePoint::handle_reset_req(Call<ResetRequest> call) {
         }
     }
-    if (this->callbacks.is_reset_allowed_callback(msg.evseId, msg.type)) {
+    ComponentVariable evse_allow_reset =
+        EvseComponentVariables::get_component_variable(evse_id, EvseComponentVariables::AllowReset);
+
+    if (msg.evseId && evse_allow_reset.has_value()) {
+        if (evse_allow_reset.value()) {
+            response.status = ResetStatusEnum::Accepted;
+        } else {
+            response.status = ResetStatusEnum::Rejected;
+        }
+    } else if (this->callbacks.is_reset_allowed_callback(msg.evseId, msg.type)) {
         // reset is allowed
         response.status = ResetStatusEnum::Accepted;
     } else {
```

**Comment by Pietfried** [comment]
Hi @barsnick , thanks for reporting this. I have added a [PR](https://github.com/EVerest/libocpp/pull/705) to include the check of `AllowReset`. I decided to keep the `is_reset_allowed_callback` call also for the EVSEs. The callback in libocpp is independent of the system interface and implementation in everest-core and is meant to be used to check if the charging station or EVSE is currently in a state in which a Reset is not possible (e.g. while updating, being busy with other operations, etc.). This can not only be derived from the `AllowReset` variable, which is a constant variable that indicates if the EVSE component supports the Reset at all.
