### ISSUE TITLE
The issue about lacking the "init.sql" when building a client that is built into the project.

### ISSUE THREAD

**Issue by LumosTZ** [EVerest/libocpp#702]
### OCPP Version

OCPP1.6

### Describe the bug

When I follow the steps in the README to build the client, and run the program using `./dist/bin/charge_point \
    --maindir ./dist \
    --conf config-docker.json`, I encounter an error as shown in the figure. I checked the corresponding file and indeed there is no `init.sql` file. Even though I created one and placed it in the correct location, I still receive this error.
![Snipaste_2024-07-21_06-55-28](https://github.com/user-attachments/assets/301e1dbc-c77f-4467-8ba8-c5183f897d0b)

**Comment by AkshayAtkarTrunexa** [comment]
Try This...!
    const fs::path sql_init_path = share_path / "core_migrations/";
![Screenshot from 2024-07-26 13-03-00](https://github.com/user-attachments/assets/fbb5a842-892e-456f-a9e7-5991806de6ac)

**Comment by Pietfried** [comment]
Fixed with https://github.com/EVerest/libocpp/pull/749
