### ISSUE TITLE
Move connectivity related functionality out of charge_point 

### ISSUE THREAD

**Issue by WilcodenBesten** [EVerest/libocpp#734]
### OCPP Version

OCPP2.0.1

### Describe the problem

`charge_point` is getting large and hard to understand and in order to pick up #410 again I'm proposing to move connectivity related functionality to it's separate class. 

Doing this separately of all the new functionality that  #410 introduced will also ease reviewing.

### Describe your solution

Introduce a `connectivity_manager` that'll:
1. Handle the web socket connection
2. Handle network connection profile logic
3. Add relevant callbacks and provide new ones where applicable in preparation for #410

**Comment by marcemmers** [comment]
It might be beneficial to refactor the opening and closing of the websocket. There is a lot of handling of this that is currently asynchronous which is a bit hard to read. It might be possible to put that into a thread and make it all sequential.

**Comment by WilcodenBesten** [comment]
> It might be beneficial to refactor the opening and closing of the websocket. There is a lot of handling of this that is currently asynchronous which is a bit hard to read. It might be possible to put that into a thread and make it all sequential.

As discussed, not necessary for now, but might do this at a later point in time if it makes sense to do so.
