### ISSUE TITLE
Support of v1.6. only compilation

### ISSUE THREAD

**Issue by Matthias-NIDEC** [EVerest/libocpp#880]
### OCPP Version

OCPP1.6

### Describe the bug

In order to compile in v1.6 only setup
option(LIBOCPP_ENABLE_V16 "Enable OCPP 1.6 in the ocpp library" ON)
option(LIBOCPP_ENABLE_V201 "Enable OCPP 2.0.1 in the ocpp library" OFF)

additional classes related to v2.0.1 are required.

See [PR] https://github.com/EVerest/libocpp/pull/879

**Comment by Pietfried** [comment]
Note for @andistorm : We should include these features in the CI as well at some point

**Comment by Pietfried** [comment]
Completed with https://github.com/EVerest/libocpp/pull/879
