### ISSUE TITLE
Harden handling of CSMS calls, if the connectorId is not in valid range.

### ISSUE THREAD

**Issue by Matthias-NIDEC** [EVerest/libocpp#883]
### OCPP Version

OCPP1.6

### Describe the bug

If from backend site, the connectorId is not in valid range, the relevant reject is answered to avoid undefined behavior.
Solution check the range:
See [PR 882.](https://github.com/EVerest/libocpp/pull/882)

**Comment by Pietfried** [comment]
Completed with https://github.com/EVerest/libocpp/pull/882
