### ISSUE TITLE
Harden message_callback against runtime error.

### ISSUE THREAD

**Issue by Matthias-NIDEC** [EVerest/libocpp#885]
### OCPP Version

OCPP1.6

### Describe the bug

Harden message_callback against runtime error, if the message form the backend can not be handled.
See https://github.com/EVerest/libocpp/pull/884

This catches set runttime_error inside ocpp/common/string.hpp
    void set(const std::string& data) {
        if (data.length() <= this->length) {
            if (this->is_valid(data)) {
                this->data = data;
            } else {
                throw std::runtime_error("String has invalid format");
            }
        } else {
            throw std::runtime_error("String length (" + std::to_string(data.length()) +
                                     ") exceeds permitted length (" + std::to_string(this->length) + ")");
        }
    }

option would be, instead of runtime_error, cut the string.

E.g. Authorize.conf with partendId longer then 20 characters.

**Comment by Pietfried** [comment]
Completed with https://github.com/EVerest/libocpp/pull/884
