### ISSUE TITLE
OCPP1.6 Offline Feature: Local List and Cache Management

### ISSUE THREAD

**Issue by Ap040** [EVerest/libocpp#895]
### OCPP Version

OCPP1.6

### Describe the bug

Hello,
I used library for my EV charger product and successfully integrate with our charger and used in charging sessions. Now, we want to explore OCPP(v1.6) Offline feature local auth list and cache management. For this I have set "AuthorizationCacheEnabled", "LocalAuthListEnabled" and "LocalAuthorizeOffline" keys to True and sent local list into charger and it is saved in db file. Now, when I disconnect internet from charger and tried to start charging using tag which is already present in locallist database but no operation is happened.
Please provide suggestion/steps to perform OCPP Offline feature testing, if above steps are not proper.

**Comment by Ap040** [comment]
Hello Team,
Please provide some update for this.

**Comment by Pietfried** [comment]
Hi @Ap040 , do you see some more information in the logs? It could be that the disconnection of the websocket has not yet been detected and this leads to a different handling of incoming tokens. You can set the `WebsocketPingInterval` to e.g. 10 seconds to detect this faster

**Comment by Ap040** [comment]
Hello,
I checked in logs and it is successfully disconnected and WebsocketPingInterval key is already set to 10 seconds. How to enable libocpp debug logs using YAML or suggest steps to do it then I can provide you detail logs.

**Comment by Ap040** [comment]
Hello @Pietfried,
Can you suggest a way to capture debug logs so, I can share you detail logs.

**Comment by Pietfried** [comment]
Hi @Ap040 , you can set the log level to e.g. `DEBG` in the [logging.ini](https://github.com/EVerest/libocpp/blob/main/config/logging.ini).

**Comment by Ap040** [comment]
Hello @Pietfried,
Thank you for your valuable response.
I changed log level and I can see more logs for all Everest modules. Here I attached log file. When OCPP is disconnected and then I plugged a CAR, and try to Authorization, it was given Invalid reason and I think, it is because of in database particular TAG expiry date is past but I want to confirm from logs but I didn't find any logs related to this. Please check logs and provide some input on this.
[Everest_OCPP_Offline.log](https://github.com/user-attachments/files/18258005/Everest_OCPP_Offline.log)
![image](https://github.com/user-attachments/assets/867e419c-b738-4d95-a98a-39956bbbf9a2)

**Comment by Ap040** [comment]
Hello @Pietfried,
After debugging and refer code flow, there was a mistake in manage "user_config.json" file which is used to store configuration keys values. Correct the mistake and now, we can able to Authorize Tag which is present in Auth Cache.
