### ISSUE TITLE
Be able to change centralSystemURI via changeConfiguration

### ISSUE THREAD

**Issue by Matthias-NIDEC** [EVerest/libocpp#901]
### OCPP Version

OCPP1.6

### Describe the problem

Inside Internal.json there are different parameters defined. 
The centralSystemURI parameter is requested to be accessible via changeConfiguration.req.

### Describe your solution

See https://github.com/EVerest/libocpp/pull/900

**Comment by Pietfried** [comment]
Completed with https://github.com/EVerest/libocpp/pull/900
